### ISSUE TITLE
error hankshake 

### ISSUE THREAD

**Issue by owencz2910** [KaustubhPatange/Moviesy#15]
nothing is loading getting error handshake.

**Comment by KaustubhPatange** [comment]
I didn't follow up, the app is working absolutely fine. Can you share some more info along with a screenshot on how to produce this error?

**Comment by owencz2910** [comment]
hi it seems to be when I'm connected to WiFi it dont work but when I'm on
mobile data it works

**Comment by KaustubhPatange** [comment]
Try to open https://yts.mx website through your wifi connection, let me know if the website opens?

**Comment by owencz2910** [comment]
hi tried to open the website but nothing and still getting the error l

**Comment by KaustubhPatange** [comment]
Seems like your ISP is blocking the website.

There is nothing I can do from my side you need to contact your provider and ask them to enable it.
