### ISSUE TITLE
[Feature Request] Add Director info

### ISSUE THREAD

**Issue by Mentallo** [KaustubhPatange/Moviesy#16]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by KaustubhPatange** [comment]
I'll see if the implementation is possible because the official [yts.mx/api](https://yts.mx/api) doesn't return any directory info so I might've to do it unofficially without breaking existing code.
