### ISSUE TITLE
"Latest" only shows recently made movies 

### ISSUE THREAD

**Issue by Mentallo** [KaustubhPatange/Moviesy#17]
YTS releases a lot classic or older movies also, why don't they show up in the Latest list?

**Comment by KaustubhPatange** [comment]
You were right, the calculation I used to show the latest movies was made by the `year` of release, not by the `date` of release. I'll add a new layout that will say "Recently Added" which will have such movies.

I'll keep this issue open until I implement this feature. You can expect a full flexed update on August 2/3 depending on the timezone you live!

**Comment by KaustubhPatange** [comment]
I didn't notice but the "Top today" chart shows Recently added movies as well.
