### ISSUE TITLE
`purchase` module is not included in the source code but referenced in the code

### ISSUE THREAD

**Issue by jiayounokim** [KaustubhPatange/Moviesy#19]
**Describe the Bug:**

In ModuleDependency.kt, there is `const val PURCHASE = ":app:purchase"` 

But there is not `purchase` module in the source code.

This purchase module is references in various places example, AutoPurchaseWorker.kt

And therefore throws error while compiling.

**Expected Behavior:**

Please include the purchase module in the GitHub source code and guide further.

**Comment by KaustubhPatange** [comment]
You need to read this compilation [guide](https://github.com/KaustubhPatange/Moviesy/wiki/Compilation-guide).
