### ISSUE TITLE
Open GitHub Discussions for this project

### ISSUE THREAD

**Issue by jiayounokim** [KaustubhPatange/Moviesy#21]
**Describe the solution you'd like:**

Open GitHub Discussions https://docs.github.com/en/discussions for this project for asking questions that do not fit into the issues and is more convenient than email.

**Describe alternatives you've considered:**

Email, Issues.

**Comment by KaustubhPatange** [comment]
There you [go](https://github.com/KaustubhPatange/Moviesy/discussions).
