### ISSUE TITLE
Getting an error : Failed due to unknown error. 

### ISSUE THREAD

**Issue by ArunBalajiR** [KaustubhPatange/Moviesy#26]
- App Version v1.7
- Affected Device(s) - Realme Narzo 20
 
**Describe the Bug:**

When I tried to enter the app for first time , Its getting an error that says Failed due to unknown error.

**Comment by KaustubhPatange** [comment]
This is a known issue https://github.com/KaustubhPatange/Moviesy/issues/25 not from my side but from yts.mx itself. The point is if you are based in Asian countries, it is likely that the app will throw this error. 

The only known solution to fix this issue is to use a VPN.
