### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by innit86** [KaustubhPatange/Moviesy#35]
![Screenshot_20211111-144227_Moviesy](https://user-images.githubusercontent.com/58744017/141309168-845c8e98-72ed-440e-b5cb-f6d24de0c521.jpg)
It's crashing all the time on S20 with Android 11.

**Comment by KaustubhPatange** [comment]
How to reproduce the crash? Can you mention the steps?

**Comment by innit86** [comment]
> How to reproduce the crash? Can you mention the steps?

It happens just few seconds after opening the app. That's all.

**Comment by KaustubhPatange** [comment]
Try the latest update the issue must be fixed.
